#pragma config(Motor,  port2,           right_motor,         tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port3,           left_motor,          tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// ^^ Configures the Motors in our code, so we can reference it by a name rather than port numbers

// Variables
/*
Variables store data
In C variables need to be given a specific data type (integers, floats(numbers with decimals), etc_
formate to define variable: [datatype] [name] = [value];<--You need a semicolon after every line in C
*/

// Physical Constants
float PI = 3.14159265358979323846;

// User Defined Vars
float default_rpm = 100.0;
float gear_ratio = 1.5;
float wheel_diam = 5.155;
float manual_offset_seconds = 0; // negative for less seconds

// Dependent Vars
float wheel_circum_feet = (wheel_diam * PI) / 12.0;
float total_revs = 30.0 / wheel_circum_feet; // Total needed revolutions
float rpm = default_rpm * gear_ratio; // Revolutions per minute multiplied by gear ratio to get the true RPM
float rps = rpm * 60.0; // Revolutions per second
float total_secs = (rps / total_revs) + manual_offset_seconds; // Total runtime of the motors to move the robot 30 ft one way in Seconds
float total_mil = total_secs * 1000.0; // Total runtime of the motors to move the robot 30 ft one way in Milliseconds

// task main(){} is where the code you want to run goes
task main()
{
	/*
	Loops- repeat the tasks inside of it until a certain condition turns false

	Conditions- are called Conditionals- basically True or False values
	However there are multiple ways to get the True or False values using OPERATORS
		int x = 0;
		//     vvv--[<=] is an example of an operator look below for more examples
		while(x <= 4){ // This while loop will continue until the variable x is LESS THAN OR EQUAL TO 4
			x++; // This increments x by one each iteration
		}

	Operators-
		+	addition or unary plus
		-	subtraction or unary minus
		*	multiplication
		/	division
		%	remainder after division (modulo division)
		=	  a = b	a = b
		+=	a += b	a = a+b
		-=	a -= b	a = a-b
		*=	a *= b	a = a*b
		/=	a /= b	a = a/b
		%=	a %= b	a = a%b
		==	Equal to 	    						5 == 3 is evaluated to 0
		>	  Greater than							5 > 3  is evaluated to 1
		<	  Less than	    						5 < 3  is evaluated to 0
		!=	Not equal to							5 != 3 is evaluated to 1
		>=	Greater than or equal to	5 >= 3 is evaluated to 1
		<=	Less than or equal to			5 <= 3 is evaluated to 0
		&&	Logical AND. True only if all operands are true	    If c = 5 and d = 2 then, expression ((c==5) && (d>5)) equals to 0.
		||	Logical OR. True only if either one operand is true	If c = 5 and d = 2 then, expression ((c==5) || (d>5)) equals to 1.
		!	  Logical NOT. True only if the operand is 0	        If c = 5 then, expression !(c==5) equals to 0.

	*/
	while(true){
		motor[right_motor] = vexRT[Ch2]; // the right_motor is configured to be controlled by the LEFT joystick(Ch2) on the controller
		motor[left_motor] = vexRT[Ch3]; // the left_motor is configured to be controlled by the LEFT joystick(Ch3) on the controller
		if(vexRT[Btn6U] ==  1){ // Only runs if the 6U Button is pressed--If statements have conditionals mentioned before and only run the code inside of it if the conditional evaluates true
			clearTimer(T1); // clears the timer object T1- http://cmra.rec.ri.cmu.edu/products/teaching_robotc_vex/radio/timers/docs/timers.pdf
			while(time1[T1] <= total_mil) { //time1 is a function that returns the robots time elapsed in Milliseconds, checks with
				motor[right_motor] = 127; // Runs right motor at full speed
				motor[left_motor] = 127; // Runs left motor at full speed
			}
			clearTimer(T1)
			while(time1[T1] <= total_mil) {
				motor[right_motor] = -127; // Runs right motor at full speed reversed
				motor[left_motor] = -127; // Runs left motor at full speed reversed
			}

		}
	}

}
